### ISSUE TITLE
Develop the first analysers

### ISSUE THREAD

**Issue by VincenzoFerme** [benchflow/analysers#2]
Develop the first analysers.

Start from the following code written in Java: [AnalyzerV2.zip](https://files.zenhub.io/5647109b8a5fa8d454c46124). It is described on the following document: 
[Marco_Argenti_thesis.pdf](https://github.com/benchflow/analysers/files/34589/Marco_Argenti_thesis.pdf). We first need to understand how to port all the concepts of the Java solution to Spark, then we can proceed with the implementation.

Evaluate also the use of the following project: http://systemml.incubator.apache.org

**Comment by Cerfoglg** [comment]
@VincenzoFerme This issue needs closing, it's been solved a while back
