### ISSUE TITLE
Discuss the algorithm used in Trial CPU and RAM Metrics

### ISSUE THREAD

**Issue by VincenzoFerme** [benchflow/analysers#29]
Discuss the algorithm used starting from what noticed on the following comments: 
- https://github.com/benchflow/analysers/pull/24#discussion-diff-54015707
- https://github.com/benchflow/analysers/pull/24#discussion-diff-54016166
- https://github.com/benchflow/analysers/pull/24#discussion-diff-54017065
- E.g., You don't need to sort twice to get min and max: https://github.com/benchflow/analysers/pull/30/files#diff-90bd08bb4caf9199a0b49a79efab618cR42

**Comment by Cerfoglg** [comment]
@VincenzoFerme This issue needs closing, since these have been solved.
