### ISSUE TITLE
Create an analyser that computes the average process duration

### ISSUE THREAD

**Issue by Cerfoglg** [benchflow/analysers#3]
As a simple analyser to start, develop a script that computes the average duration of a process from the process table on the benchflow Cassandra database.

**Comment by VincenzoFerme** [comment]
@Cerfoglg it should does so for each of the repetition, and then for the whole experiment. For the whole experiment, this should be the [weighted mean](http://mathworld.wolfram.com/WeightedMean.html) of the averages of each of the repetition. Please update the issue description, and discuss here how do you plan to implement this, before the actual implementation.

**Comment by Cerfoglg** [comment]
@VincenzoFerme Where do we store the results of the analysis per repetition? Somewhere in Cassandra? It would make sense, since we obviously want the script to work on each repetition as they come, and then once all are done a new script will compute the weighted average (or the same script given certain arguments).

So let's say in this case we have a table in Cassandra storing the experiment_id, replication_num, and duration_avg. Once the average it computed for the processes given the rep num and experiment, we store the average in that table, and once it's all there we launch a new analysis to retrieve those data and compute the weighted average, and then store that in another table that has experiment_id and duration_weighted_avg for instance.

This should also be appliable to any metric in theory, and it shouldn't be that much more data to store on Cassandra.

**Comment by VincenzoFerme** [comment]
@Cerfoglg I created a dedicated issue to discuss the database design: https://github.com/benchflow/analysers/issues/6. Can you please move your discussion there? Thank you. Once done we can start a discussion there about your proposal. Here you should discuss about the design of the analyzes themself.

**Comment by VincenzoFerme** [comment]
@Cerfoglg I want to point out some interesting characteristics and functionality offered by Cassandra that might be useful for simple analysers:
- **Aggregates**: https://docs.datastax.com/en/cql/3.3/cql/cql_using/useQueryStdAggregate.html
- **Custom Aggregates** definition: http://christopher-batey.blogspot.ch/2015/05/cassandra-aggregates-min-max-avg-group.html
- At some point, for some analysers, it might be useful to use asynch triggers: https://maxgrinev.wordpress.com/2010/07/23/extending-cassandra-with-asynchronous-triggers/

**Comment by Cerfoglg** [comment]
@VincenzoFerme I'll definitely look into using aggregates, though I may have to alter our Cassandra definition (or rather, add in the aggregate definitions and functions). I'll look into testing out both ways of doing it.
