### ISSUE TITLE
Alter analysers to take container ids into account

### ISSUE THREAD

**Issue by Cerfoglg** [benchflow/analysers#35]
Our current implementation of the analyser scripts do not take containers into account for the data, but rather they calculate the metrics over all data regardless of the container. This should be changed, as we will have data belonging to multiple containers, and we want the metrics to be computed for each of them.

Alter the cpu and ram analysers so that all metrics are computed for each container, rather than over the entire set of data.

**Comment by VincenzoFerme** [comment]
@Cerfoglg this also alter the [database](https://github.com/benchflow/benchflow/blob/dev/database_schemas/cassandra/benchflow.cql)

**Comment by Cerfoglg** [comment]
@VincenzoFerme This issue needs closing, it's been solved.

**Comment by VincenzoFerme** [comment]
@Cerfoglg ok, next time please remember to map to a pull request
