### ISSUE TITLE
Create configurations for analysers

### ISSUE THREAD

**Issue by Cerfoglg** [benchflow/analysers#40]
For analyers such as throughput, number of process instances and process duration  for example we are using a variable hardcoded in the script to choose how many initial processes to filter away before computing the metrics. It's best to have for all analysers that require variables such as this, that are not needed to be passed dynamically by the Spark Tasks Sender, to create configuration files to specify them (this should be a SUT plugin configuration file).

**Comment by Cerfoglg** [comment]
@VincenzoFerme Similarly to how configurations for data transformers is handled, now we have yaml configuration files that contain SUT specific settings (such as the number of initial processes to cut).

The format of these files is SUT_Name.analysers.yaml

**Comment by VincenzoFerme** [comment]
Already done.
