### ISSUE TITLE
Investigate whether it is needed to store an array with the size of the total number of available cores

### ISSUE THREAD

**Issue by VincenzoFerme** [benchflow/analysers#54]
Investigate the following: https://github.com/benchflow/analysers/pull/51#discussion-diff-56677844.

@Cerfoglg if possible, discuss here why do you actually need it with an example.

**Comment by Cerfoglg** [comment]
@VincenzoFerme As previously discussed, we have the array with all the cores to maintain the indexes of the cores as reported by Docker. However we do now get that size from the host info we collect.
