### ISSUE TITLE
Make the throughput metrics dependant on number of process instances and execution time

### ISSUE THREAD

**Issue by VincenzoFerme** [benchflow/analysers#58]
See: https://github.com/benchflow/spark-tasks-sender/issues/30 and https://github.com/benchflow/analysers/issues/27

**Comment by Cerfoglg** [comment]
@VincenzoFerme This was fixed in https://github.com/benchflow/analysers/pull/75

**Comment by VincenzoFerme** [comment]
@Cerfoglg I don't see yet the dependency management in https://github.com/benchflow/analysers/blob/dev/analysers.scheduler.configuration.yml
