### ISSUE TITLE
Compute metrics/statistics at process and feature level

### ISSUE THREAD

**Issue by Cerfoglg** [benchflow/analysers#68]
Currently we compute metrics/statistics only at WfMS engine level, meaning we aggregate all processes. 

Add the computation of the same metrics/statistics at process (for each distinct process in the workload mix) and feature level (for each distinct process for each distinct activity identifier in the workload mix), meaning computing them for every individual process and construct as well.

For construct level, we also want to store the activity type and activity name as well. Distinguish the construct for name and type, and constructs belonging to the same process are counted separately.

Make the identifier of the process, the name of the activity and the identifier of the activity type of the different processes / features configurable.

**Comment by VincenzoFerme** [comment]
Resolved in #75
