### ISSUE TITLE
Compute Efficiency of Resource Utilisation

### ISSUE THREAD

**Issue by Cerfoglg** [benchflow/analysers#69]
Add the computation of the efficency for `ram` and `cpu`, which is defined as:

`Integral(data)/(max(data)*num_data_points)`

This effectively computes how much the resource has been used by defining the ratio between the integral of the data and the rectangle area obtained by multiplying the maximum and the number of data points.

For both `cpu` and `ram`, compute efficiency relative (relative efficiency) to the max of the data as well as the max possible usage (absolute efficiency). For `cpu` it's 100% usage max, for `ram` it can be read in `container properties` if a limit was set for the container, or `host properties` if no limit was set on the container.

**Comment by VincenzoFerme** [comment]
Resolved in #75
